DATA:
  data_root: ~/data/ade20k_data
  train_list: data/ade20k/list/training.txt
  val_list: data/ade20k/list/validation.txt
  classes: 150

TRAIN:
  arch: bcanet
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 473
  train_w: 473
  multi_grid: [1,2,4]
  ohem: False
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  seg_weight: 1.0
  edge_weight: 1.0
  att_weight: 0.0
  aux_weight: 0.4
  train_gpu: [0,1]
  workers: 12  # data loader workers
  batch_size: 12  # batch size for training
  batch_size_val: 4  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.001
  epochs: 120
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0005
  manual_seed:
  print_freq: 10
  save_freq: 1
  val_freq: 1
  save_path: exp/ade20k/bcanet50/model
  weight:    # path to initial weight (default: none)
  resume:   # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6770
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: data/ade20k/list/validation.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/ade20k/bcanet50/model/train_epoch_120.pth  # evaluation model path
  save_folder: exp/ade20k/bcanet50/result/val/ss  # results save folder
  colors_path: data/ade20k/ade20k_colors.txt  # path of dataset colors
  names_path: data/ade20k/ade20k_names.txt  # path of dataset category names